"use client";
import React, { useEffect, useState } from 'react';

export default function ReportsPage() {
    const [data, setData] = useState(null);
    const [knowledge, setKnowledge] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        Promise.all([
            fetch('/clinic_insight.json').then(r => r.json()),
            fetch('/medical_knowledge.json').then(r => r.json())
        ]).then(([d, k]) => { setData(d); setKnowledge(k); setLoading(false); })
            .catch(() => setLoading(false));
    }, []);

    const handleDownloadReport = () => {
        if (!data || !knowledge) return;

        // Normalize data
        let processedData = data;
        if (Array.isArray(data)) {
            processedData = {};
            data.forEach(record => {
                const s = record.Symptom;
                const m = record.Month;
                if (s && m) {
                    if (!processedData[s]) processedData[s] = {};
                    processedData[s][m] = (processedData[s][m] || 0) + 1;
                }
            });
        }

        const symptoms = Object.keys(processedData);
        const months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'].filter(m =>
            symptoms.some(s => processedData[s][m] !== undefined)
        );
        const totalCases = symptoms.reduce((s, sym) => s + months.reduce((ms, m) => ms + (processedData[sym][m] || 0), 0), 0);
        const topSymptom = symptoms.map(s => ({ name: s, total: months.reduce((sum, m) => sum + (processedData[s][m] || 0), 0) })).sort((a, b) => b.total - a.total)[0];

        const reportText = `
╔══════════════════════════════════════════════════════════════╗
║             MEDIKLY — HEALTH ANALYTICS REPORT               ║
║                   Generated: ${new Date().toLocaleDateString()}                     ║
╠══════════════════════════════════════════════════════════════╣

EXECUTIVE SUMMARY
─────────────────────
• Total Cases Analyzed: ${totalCases}
• Monitoring Period: ${months[0]} - ${months[months.length - 1]} 2026
• Symptoms Tracked: ${symptoms.length}
• Top Symptom: ${topSymptom.name} (${topSymptom.total} cases)

MONTHLY BREAKDOWN
─────────────────────
${months.map(m => {
            const monthTotal = symptoms.reduce((s, sym) => s + (processedData[sym][m] || 0), 0);
            const breakdown = symptoms.map(sym => `    ${sym}: ${processedData[sym][m] || 0}`).join('\n');
            return `${m} (Total: ${monthTotal})\n${breakdown}`;
        }).join('\n\n')}

KEY FINDINGS
─────────────────────
1. Peak symptom activity identified: ${topSymptom.name} (${topSymptom.total} total cases)
2. Seasonal correlation detected across ${months.length} months.
3. Analysis confirms distinct symptom clusters matching medical protocols.
4. Monitoring period shows ${totalCases > 500 ? 'high' : 'moderate'} patient volume.

AI-DERIVED INSIGHTS
─────────────────────
• Dynamic analysis detected ${totalCases} health events.
• Temporal patterns identified within ${months[0]} to ${months[months.length - 1]}.
• Medical knowledge base correlated with recognized disease profiles.

TREATMENT PROTOCOLS
─────────────────────
${knowledge.diseases.map(d => `${d.name} (${d.severity} severity)
  Symptoms: ${d.symptoms.join(', ')}
  Treatment: ${d.curing}
  Medicine: ${d.medicine}`).join('\n\n')}

ASSUMPTIONS & LIMITATIONS
─────────────────────
• Data is derived from synthesized clinic records.
• Each count represents a discrete patient encounter.
• Symptom clustering provides clinical decision support, not diagnosis.

═══════════════════════════════════════════════════════════════
Report generated by Medikly Data Science Platform
═══════════════════════════════════════════════════════════════
    `.trim();

        const blob = new Blob([reportText], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `Medikly_Report_${new Date().toISOString().split('T')[0]}.txt`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    };

    if (loading || !data) return (
        <div className="flex items-center justify-center h-screen">
            <div className="w-8 h-8 rounded-full border-4 border-t-transparent animate-spin" style={{ borderColor: '#A5D6A7', borderTopColor: 'transparent' }} />
        </div>
    );

    // Normalize data: Handle both aggregated object format and raw record array format
    let processedData = data;
    if (Array.isArray(data)) {
        processedData = {};
        data.forEach(record => {
            const s = record.Symptom;
            const m = record.Month;
            if (s && m) {
                if (!processedData[s]) processedData[s] = {};
                processedData[s][m] = (processedData[s][m] || 0) + 1;
            }
        });
    }

    const symptoms = Object.keys(processedData);
    const months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'].filter(m =>
        symptoms.some(s => processedData[s][m] !== undefined)
    );
    const totalCases = Array.isArray(data) ? data.length : symptoms.reduce((s, sym) => s + months.reduce((ms, m) => ms + (processedData[sym][m] || 0), 0), 0);

    return (
        <div className="p-6 lg:p-10 space-y-10 max-w-[1000px] mx-auto">
            <div>
                <h1 className="text-3xl font-black tracking-tight" style={{ color: '#1a1a2e' }}>
                    Monthly <span style={{ color: '#2E7D32' }}>Report</span>
                </h1>
                <p className="text-sm mt-1" style={{ color: '#6b7c8a' }}>Download a complete insights summary for stakeholders</p>
            </div>

            {/* Report Preview Card */}
            <div className="bg-white rounded-3xl shadow-lg border border-gray-100 overflow-hidden">
                <div className="p-8 lg:p-10" style={{ background: '#1a1a2e' }}>
                    <div className="flex items-center gap-4">
                        <div className="w-14 h-14 rounded-2xl flex items-center justify-center text-3xl" style={{ background: 'rgba(255,255,255,0.1)' }}></div>
                        <div>
                            <h3 className="text-lg font-black text-white">Medikly Quarterly Report</h3>
                            <p className="text-xs text-white/50">January - March 2026 | Auto-generated</p>
                        </div>
                    </div>
                </div>

                <div className="p-8 lg:p-10 space-y-8">
                    {/* Quick Stats */}
                    <div className="grid grid-cols-3 gap-4">
                        <div className="text-center p-4 rounded-2xl" style={{ background: '#E8F5E9' }}>
                            <p className="text-2xl font-black" style={{ color: '#2E7D32' }}>{totalCases}</p>
                            <p className="text-[10px] font-bold uppercase tracking-widest" style={{ color: '#6b7c8a' }}>Total Cases</p>
                        </div>
                        <div className="text-center p-4 rounded-2xl" style={{ background: '#E8F5E9' }}>
                            <p className="text-2xl font-black" style={{ color: '#2E7D32' }}>{symptoms.length}</p>
                            <p className="text-[10px] font-bold uppercase tracking-widest" style={{ color: '#6b7c8a' }}>Symptoms</p>
                        </div>
                        <div className="text-center p-4 rounded-2xl" style={{ background: '#E8F5E9' }}>
                            <p className="text-2xl font-black" style={{ color: '#2E7D32' }}>4</p>
                            <p className="text-[10px] font-bold uppercase tracking-widest" style={{ color: '#6b7c8a' }}>Diseases</p>
                        </div>
                    </div>

                    {/* Report Sections */}
                    <div className="space-y-4">
                        <p className="text-[10px] font-black uppercase tracking-widest" style={{ color: '#9e9e9e' }}>Report Includes</p>
                        {[
                            { title: 'Executive Summary', desc: 'Overview of total cases, top symptoms, and peak months' },
                            { title: 'Monthly Breakdown', desc: 'Detailed case counts per symptom per month' },
                            { title: 'Key Findings', desc: '4 major clinical discoveries from the data' },
                            { title: 'AI-Derived Insights', desc: 'Pattern correlations and seasonal diagnoses' },
                            { title: 'Treatment Protocols', desc: 'Recommended treatments and medicines for detected conditions' },
                            { title: 'Assumptions & Limitations', desc: 'Scientific disclosure of data constraints' },
                        ].map((item, i) => (
                            <div key={i} className="p-4 rounded-2xl border border-gray-100 hover:shadow-sm transition-shadow">
                                <div>
                                    <p className="text-sm font-bold" style={{ color: '#1a1a2e' }}>{item.title}</p>
                                    <p className="text-[10px]" style={{ color: '#6b7c8a' }}>{item.desc}</p>
                                </div>
                            </div>
                        ))}
                    </div>

                    {/* Download Button */}
                    <button
                        onClick={handleDownloadReport}
                        className="w-full py-4 rounded-2xl text-white font-black uppercase tracking-widest text-sm shadow-lg hover:scale-[1.02] active:scale-95 transition-all"
                        style={{ background: '#2E7D32' }}
                    >
                        Download Full Report (.txt)
                    </button>
                </div>
            </div>
        </div>
    );
}
