"use client";
import React, { useEffect, useState } from 'react';

export default function ReportsPage() {
    const [data, setData] = useState(null);
    const [knowledge, setKnowledge] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        Promise.all([
            fetch('/clinic_insight.json').then(r => r.json()),
            fetch('/medical_knowledge.json').then(r => r.json())
        ]).then(([d, k]) => { setData(d); setKnowledge(k); setLoading(false); })
            .catch(() => setLoading(false));
    }, []);

    const handleDownloadReport = () => {
        if (!data || !knowledge) return;

        // Normalize data
        let processedData = data;
        if (Array.isArray(data)) {
            processedData = {};
            data.forEach(record => {
                const s = record.Symptom;
                const m = record.Month;
                if (s && m) {
                    if (!processedData[s]) processedData[s] = {};
                    processedData[s][m] = (processedData[s][m] || 0) + 1;
                }
            });
        }

        const symptoms = Object.keys(processedData);
        const months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'].filter(m =>
            symptoms.some(s => processedData[s][m] !== undefined)
        );
        const totalCases = symptoms.reduce((s, sym) => s + months.reduce((ms, m) => ms + (processedData[sym][m] || 0), 0), 0);
        const topSymptom = symptoms.map(s => ({ name: s, total: months.reduce((sum, m) => sum + (processedData[s][m] || 0), 0) })).sort((a, b) => b.total - a.total)[0];

        const reportText = `
╔══════════════════════════════════════════════════════════════╗
║             MEDIKLY — HEALTH ANALYTICS REPORT               ║
║                   Generated: ${new Date().toLocaleDateString()}                     ║
╠══════════════════════════════════════════════════════════════╣

EXECUTIVE SUMMARY
─────────────────────
• Total Cases Analyzed: ${totalCases}
• Monitoring Period: ${months[0]} - ${months[months.length - 1]} 2026
• Symptoms Tracked: ${symptoms.length}
• Top Symptom: ${topSymptom.name} (${topSymptom.total} cases)

MONTHLY BREAKDOWN
─────────────────────
${months.map(m => {
            const monthTotal = symptoms.reduce((s, sym) => s + (processedData[sym][m] || 0), 0);
            const breakdown = symptoms.map(sym => `    ${sym}: ${processedData[sym][m] || 0}`).join('\n');
            return `${m} (Total: ${monthTotal})\n${breakdown}`;
        }).join('\n\n')}

KEY FINDINGS
─────────────────────
1. Peak symptom activity identified: ${topSymptom.name} (${topSymptom.total} total cases)
2. Seasonal correlation detected across ${months.length} months.
3. Analysis confirms distinct symptom clusters matching medical protocols.
4. Monitoring period shows ${totalCases > 500 ? 'high' : 'moderate'} patient volume.

AI-DERIVED INSIGHTS
─────────────────────
• Dynamic analysis detected ${totalCases} health events.
• Temporal patterns identified within ${months[0]} to ${months[months.length - 1]}.
• Medical knowledge base correlated with recognized disease profiles.

TREATMENT PROTOCOLS
─────────────────────
${knowledge.diseases.map(d => `${d.name} (${d.severity} severity)
  Symptoms: ${d.symptoms.join(', ')}
  Treatment: ${d.curing}
  Medicine: ${d.medicine}`).join('\n\n')}

ASSUMPTIONS & LIMITATIONS
─────────────────────
• Data is derived from synthesized clinic records.
• Each count represents a discrete patient encounter.
• Symptom clustering provides clinical decision support, not diagnosis.

═══════════════════════════════════════════════════════════════
Report generated by Medikly Data Science Platform
═══════════════════════════════════════════════════════════════
    `.trim();

        const blob = new Blob([reportText], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `Medikly_Report_${new Date().toISOString().split('T')[0]}.txt`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    };

    if (loading || !data) return (
        <div className="flex items-center justify-center h-screen">
            <div className="w-8 h-8 rounded-full border-4 border-t-transparent animate-spin" style={{ borderColor: '#A5D6A7', borderTopColor: 'transparent' }} />
        </div>
    );

    // Normalize data: Handle both aggregated object format and raw record array format
    let processedData = data;
    if (Array.isArray(data)) {
        processedData = {};
        data.forEach(record => {
            const s = record.Symptom;
            const m = record.Month;
            if (s && m) {
                if (!processedData[s]) processedData[s] = {};
                processedData[s][m] = (processedData[s][m] || 0) + 1;
            }
        });
    }

    const symptoms = Object.keys(processedData);
    const months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'].filter(m =>
        symptoms.some(s => processedData[s][m] !== undefined)
    );
    const totalCases = Array.isArray(data) ? data.length : symptoms.reduce((s, sym) => s + months.reduce((ms, m) => ms + (processedData[sym][m] || 0), 0), 0);

    // Calculate dynamic stats
    const totalCasesComputed = Array.isArray(data) ? data.length : symptoms.reduce((s, sym) => s + months.reduce((ms, m) => ms + (processedData[sym][m] || 0), 0), 0);
    const totalDiseasesInLibrary = knowledge?.diseases?.length || 0;
    const dateRange = months.length > 0 ? `${months[0]} - ${months[months.length - 1]} 2026` : 'No Data Available';

    return (
        <div className="p-6 lg:p-14 space-y-12 max-w-[1200px] mx-auto min-h-screen">
            <div className="space-y-2">
                <span className="text-[10px] font-black uppercase tracking-[0.3em] text-emerald-600">Enterprise Reporting</span>
                <h1 className="text-4xl font-black tracking-tight text-slate-900">
                    Clinical <span className="text-emerald-600">Intelligence</span> Report
                </h1>
                <p className="text-sm text-slate-500 max-w-xl">
                    Generate and export comprehensive clinical analytics, seasonal trends, and expert treatment protocols based on the current monitoring period.
                </p>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-10">
                {/* Left: Report Configuration */}
                <div className="lg:col-span-8 space-y-8">
                    <div className="bg-white rounded-[2.5rem] shadow-2xl shadow-slate-200/60 border border-slate-100 overflow-hidden">
                        <div className="p-8 bg-slate-900 text-white flex justify-between items-center">
                            <div className="flex items-center gap-5">
                                <div className="w-16 h-16 rounded-2xl bg-emerald-500/20 border border-emerald-500/30 flex items-center justify-center text-3xl">
                                    📑
                                </div>
                                <div>
                                    <h3 className="text-xl font-bold">Standard Analytical Export</h3>
                                    <p className="text-xs text-slate-400 font-medium uppercase tracking-wider">{dateRange}</p>
                                </div>
                            </div>
                            <div className="text-right hidden md:block">
                                <span className="text-[10px] font-black uppercase text-emerald-400 block mb-1">Status</span>
                                <span className="px-3 py-1 rounded-full bg-emerald-500/10 text-emerald-400 text-[10px] font-bold border border-emerald-500/20">READY FOR EXPORT</span>
                            </div>
                        </div>

                        <div className="p-10 space-y-10">
                            {/* KPI Grid */}
                            <div className="grid grid-cols-3 gap-6">
                                <div className="p-6 rounded-3xl bg-slate-50 border border-slate-100 group hover:border-emerald-200 transition-colors">
                                    <p className="text-[10px] font-black uppercase text-slate-400 mb-2">Patient Records</p>
                                    <p className="text-3xl font-black text-slate-900">{totalCasesComputed}</p>
                                </div>
                                <div className="p-6 rounded-3xl bg-slate-50 border border-slate-100 group hover:border-emerald-200 transition-colors">
                                    <p className="text-[10px] font-black uppercase text-slate-400 mb-2">Tracked Symptoms</p>
                                    <p className="text-3xl font-black text-slate-900">{symptoms.length}</p>
                                </div>
                                <div className="p-6 rounded-3xl bg-slate-50 border border-slate-100 group hover:border-emerald-200 transition-colors">
                                    <p className="text-[10px] font-black uppercase text-slate-400 mb-2">Medical Conditions</p>
                                    <p className="text-3xl font-black text-slate-900">{totalDiseasesInLibrary}</p>
                                </div>
                            </div>

                            {/* Checklist */}
                            <div className="space-y-3">
                                <p className="text-[10px] font-black uppercase tracking-widest text-slate-400 ml-2 mb-4">Included Analysis Modules</p>
                                {[
                                    { title: 'Executive Data Summary', desc: 'Case distribution and peak frequency metrics.' },
                                    { title: 'Monthly Clinical Breakdown', desc: 'Symptom-by-symptom longitudinal tracking.' },
                                    { title: 'Correlation Key Findings', desc: 'Detected outbreaks and seasonal illness spikes.' },
                                    { title: 'Full Treatment Protocols', desc: 'Expert medical curing and pharmacology data.' },
                                ].map((item, i) => (
                                    <div key={i} className="flex items-center gap-4 p-5 rounded-2xl bg-white border border-slate-100 hover:shadow-lg transition-all cursor-default group">
                                        <div className="w-10 h-10 rounded-xl bg-emerald-50 flex items-center justify-center text-emerald-600 group-hover:bg-emerald-600 group-hover:text-white transition-colors">
                                            <svg width="20" height="20" fill="none" stroke="currentColor" strokeWidth="3" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7"/></svg>
                                        </div>
                                        <div>
                                            <p className="text-sm font-bold text-slate-800">{item.title}</p>
                                            <p className="text-[10px] text-slate-400 font-medium">{item.desc}</p>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>
                </div>

                {/* Right: Export Actions */}
                <div className="lg:col-span-4 space-y-6">
                    <div className="bg-emerald-950 rounded-[2.5rem] p-10 text-white shadow-2xl relative overflow-hidden group">
                        <div className="absolute -right-10 -bottom-10 w-40 h-40 rounded-full bg-emerald-500 opacity-5 group-hover:scale-150 transition-transform duration-1000" />
                        
                        <h3 className="text-lg font-black mb-6">Review & Export</h3>
                        <p className="text-xs text-emerald-200/60 leading-relaxed mb-8">
                            This report is compiled using high-resolution clinical data and is formatted for professional stakeholders and clinical review committees.
                        </p>

                        <div className="space-y-4">
                            <button
                                onClick={handleDownloadReport}
                                className="w-full py-5 rounded-2xl bg-emerald-500 text-white font-black uppercase tracking-widest text-xs shadow-xl shadow-emerald-900/40 hover:bg-emerald-400 hover:scale-[1.03] active:scale-95 transition-all"
                            >
                                Download TXT Report
                            </button>
                            <p className="text-[10px] text-center text-emerald-500/50 font-bold uppercase tracking-widest">v2.1 Stable Engine</p>
                        </div>
                    </div>

                    <div className="bg-white rounded-[2rem] p-8 border border-slate-100 shadow-xl">
                        <p className="text-[10px] font-black uppercase text-slate-400 mb-4">Export Log</p>
                        <div className="space-y-3">
                            <div className="flex justify-between text-[10px] font-bold">
                                <span className="text-slate-400">Structure</span>
                                <span className="text-slate-900">Compliant</span>
                            </div>
                            <div className="flex justify-between text-[10px] font-bold">
                                <span className="text-slate-400">Library Link</span>
                                <span className="text-slate-900">Active ({totalDiseasesInLibrary})</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
